[features]
seeds = false
skip-lint = false
[programs.localnet]
example1_lottery = "CRTqpK925UGfmxJxSpncim7hF5RRAoFvtvLggQHHMvf8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/Documents/Playground/web3/solana/keypairs/token-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
